# -*- coding: utf-8 -*-
"""RNN_filtro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t89lZ9Iti9WdFeXUSGabsy9ZZcjTgFy-
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

# ---------------------------------------------------
# 1. CARGAR DATASET
# ---------------------------------------------------

df = pd.read_csv("dataset_agua_queretaro_4000.csv")

print(df.head())

# ---------------------------------------------------
# 2. CREAR ETIQUETA DE RUIDO (0 = normal, 1 = ruido)
# ---------------------------------------------------

def detectar_ruido(row):

    if row["ph"] < 6 or row["ph"] > 9:
        return 1

    if row["temperatura_c"] < 10 or row["temperatura_c"] > 35:
        return 1

    if row["turbidez_ntu"] > 20:
        return 1

    if row["oxigeno_mg_l"] < 2:
        return 1

    if row["conductividad_us_cm"] > 2200:
        return 1

    return 0

df["ruido"] = df.apply(detectar_ruido, axis=1)

print(df["ruido"].value_counts())

# ---------------------------------------------------
# 3. VARIABLES DE ENTRADA
# ---------------------------------------------------

features = [
    "ph",
    "temperatura_c",
    "turbidez_ntu",
    "oxigeno_mg_l",
    "conductividad_us_cm",
    "tds_ppm",
    "nitratos_mg_l",
    "profundidad_m"
]

X = df[features].values
y = df["ruido"].values

# ---------------------------------------------------
# 4. NORMALIZAR
# ---------------------------------------------------

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# ---------------------------------------------------
# 5. CONVERTIR A SECUENCIAS PARA RNN
# (usa ventanas de 10 lecturas consecutivas)
# ---------------------------------------------------

window = 10

X_seq = []
y_seq = []

for i in range(len(X) - window):
    X_seq.append(X[i:i+window])
    y_seq.append(y[i+window])

X_seq = np.array(X_seq)
y_seq = np.array(y_seq)

print("Shape X:", X_seq.shape)
print("Shape y:", y_seq.shape)

# ---------------------------------------------------
# 6. TRAIN / TEST
# ---------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X_seq, y_seq,
    test_size=0.20,
    random_state=42,
    stratify=y_seq
)

# ---------------------------------------------------
# 7. MODELO LSTM
# ---------------------------------------------------

model = Sequential()

model.add(LSTM(64, input_shape=(window, X_seq.shape[2]), return_sequences=False))
model.add(Dropout(0.2))

model.add(Dense(32, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ---------------------------------------------------
# 8. ENTRENAMIENTO
# ---------------------------------------------------

history = model.fit(
    X_train,
    y_train,
    epochs=25,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

# ---------------------------------------------------
# 9. EVALUACIÓN
# ---------------------------------------------------

loss, acc = model.evaluate(X_test, y_test)
print("\nAccuracy:", acc)

# ---------------------------------------------------
# 10. PREDICCIONES
# ---------------------------------------------------

pred = model.predict(X_test)
pred = (pred > 0.5).astype(int)

print("\nMatriz de Confusión")
print(confusion_matrix(y_test, pred))

print("\nReporte")
print(classification_report(y_test, pred))

# ---------------------------------------------------
# 11. GUARDAR MODELO
# ---------------------------------------------------

model.save("modelo_lstm_ruido_agua.h5")

print("\nModelo guardado correctamente.")

import matplotlib.pyplot as plt

plt.plot(history.history["accuracy"], label="train")
plt.plot(history.history["val_accuracy"], label="val")
plt.legend()
plt.title("Accuracy")
plt.show()

plt.plot(history.history["loss"], label="train")
plt.plot(history.history["val_loss"], label="val")
plt.legend()
plt.title("Loss")
plt.show()

